### ISSUE TITLE
Failed loading gx_cabinet and NAM for old CPUS - SOLVED

### ISSUE THREAD

**Issue by rusk911** [raidolo/mod-docker#1]
Don't know if its docker image issue. Getting this error trying to load gx_cabinet
lilv_lib_open(): error: Failed to open library /usr/lib/lv2/gx_cabinet.lv2/gx_cabinet.so (libzita-resampler.so.1: cannot open shared object file: No such file or directory)

**Comment by raidolo** [comment]
It could be an issue with the build, but it was not my purpose to fix every plugin. Many others could not work properly, but that means they don't work even without using docker and you compile them yourself. Maybe there are some dependencies not fully respected. I suggest you to use the Impulse Response cabinet by Cabism for now. I'll try to look into it, but I'm not sure it worth it, because right now there are new developments from MOD regarding a full desktop app for Linux, I think it will be better to follow this path than hacking the mod-ui to let it run on the desktop. I'm actually testing the Mod-app, to see what they have changed...

**Comment by rusk911** [comment]
wow great news. Totally agree. In that case docker image development is not relevant.
BTW after first day it stopped working for me at all. Seems mod-ui can't find audio interface.
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED

**Comment by raidolo** [comment]
It's not that.... I have the same error, but then it goes up. Did you start jack in advance? Yeah regarding the docker build, I've fixed some stuff regarding the midi switch of the pedalboards and the snapshots, which currently seems broken in the mod-app and also I'm having some weird issue with the Jack connection of the Left and Right channel, sometime I have to unplug the wires on the left panel, so it's not ok for stability, but we will see what happens.

**Comment by rusk911** [comment]
Yes, I have jack running at system startup. Anyway. Docker downloaded over 12 GB of images. I won't keep it just for nice mod-ui. All plugins are installed locally and can be used with Ardour and Carla.

**Comment by raidolo** [comment]
Regarding the Guitarix plugin, I've found this https://community.blokas.io/t/guide-many-more-extra-modep-plugins/292/9 it seems I have to add libzita package in the docker image. I'll see what I can do. Maybe I'll rebuild the image adding just that. Thanks for the feedback.

**Comment by raidolo** [comment]
> Yes, I have jack running at system startup. Anyway. Docker downloaded over 12 GB of images. I won't keep it just for nice mod-ui. All plugins are installed locally and can be used with Ardour and Carla.

The image itself it's around 4.5GB... not 12. How is that possibile?

**Comment by rusk911** [comment]
I have installed docker just to try mod-ui image. Now I have this:

```
$ docker images
REPOSITORY       TAG        IMAGE ID       CREATED        SIZE
<none>           <none>     48be0db75fb2   2 days ago     2.76GB
mod-host         latest     cd5700f7739f   2 days ago     1.88GB
<none>           <none>     e331f99fb5e3   2 days ago     128MB
raidolo/mod-ui   latest     0325d801570d   5 days ago     4.49GB
debian           bookworm   676aedd4776f   2 weeks ago    117MB
ubuntu           latest     e4c58958181a   3 weeks ago    77.8MB
raidolo/mod-ui   <none>     ac00823e2434   3 months ago   3.58GB

```

**Comment by rusk911** [comment]
But this is from both mod-docker repositories.

**Comment by raidolo** [comment]
Clean all the images and the containers pruning them and redownload only the raidolo/mod-ui:latest. You don't need all the images shown in the log. 
Additionally, I was thinking to remove all the plugins that do not have a GUI from the docker, because loading the gui with such huge amount of plugins is very heavy and I found myself not using the plugins without the gui, it's ugly and it makes me sad :)

**Comment by raidolo** [comment]
```
raid@beelink:~$ docker image ls
REPOSITORY       TAG       IMAGE ID       CREATED      SIZE
raidolo/mod-ui   latest    0325d801570d   5 days ago   4.49GB
raid@beelink:~$
```

**Comment by raidolo** [comment]
> Don't know if its docker image issue. Getting this error trying to load gx_cabinet lilv_lib_open(): error: Failed to open library /usr/lib/lv2/gx_cabinet.lv2/gx_cabinet.so (libzita-resampler.so.1: cannot open shared object file: No such file or directory)


I've added the libzita in the docker image. Please pull the latest image version. It seems working now, along all the other Guitarix Fuzz plugins. :) It was quicker than i thought.

Let me know.

Cheers.

**Comment by rusk911** [comment]
can't check. Same error, cannot get audio device. mod-ui is up and running, but showing connection error in browser.
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED

**Comment by raidolo** [comment]
> can't check. Same error, cannot get audio device. mod-ui is up and running, but showing connection error in browser. mod-ui | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO mod-ui | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED

Could you post the whole log?

**Comment by rusk911** [comment]
```
~/mod-docker$ ./run_docker.sh 
Using default tag: latest
latest: Pulling from raidolo/mod-ui
Digest: sha256:767f6e644fc85842a9c1e428d7869aba69b0f91f3278db1e079a36fbe8eb9aaf
Status: Image is up to date for raidolo/mod-ui:latest
docker.io/raidolo/mod-ui:latest
Starting mod-ui ... done
Attaching to mod-ui
mod-ui           | PUID 1000
mod-ui           | PGID 1000
mod-ui           | useradd: user 'abc' already exists
mod-ui           | usermod: no changes
mod-ui           | Forking... child PID: 28
mod-ui           | lilv_world_load_bundle(): warning: Replacing version 0.0 of <http://code.google.com/p/amsynth/amsynth> from <file:///usr/lib/x86_64-linux-gnu/lv2/amsynth.lv2/>
mod-ui           | lilv_world_load_bundle(): note: New version 1.5 found in <file:///usr/lib/lv2/amsynth.lv2/>
mod-ui           | lilv_world_load_bundle(): warning: Ignoring bundle <file:///usr/lib/lv2/Vex.lv2/>
mod-ui           | lilv_world_load_bundle(): note: Newer version of <urn:juce:Vex> loaded from <file:///usr/lib/lv2/vex.lv2/>
mod-ui           | mod-host ready!
mod-ui           |  * Serving Flask app 'browsepy'
mod-ui           |  * Debug mode: off
mod-ui           | lilv_world_load_bundle(): warning: Replacing version 0.0 of <http://code.google.com/p/amsynth/amsynth> from <file:///usr/lib/x86_64-linux-gnu/lv2/amsynth.lv2/>
mod-ui           | lilv_world_load_bundle(): note: New version 1.5 found in <file:///usr/lib/lv2/amsynth.lv2/>
mod-ui           | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
mod-ui           |  * Running on all addresses (0.0.0.0)
mod-ui           |  * Running on http://127.0.0.1:8081
mod-ui           |  * Running on http://172.19.0.2:8081
mod-ui           | Press CTRL+C to quit
mod-ui           | lilv_world_load_bundle(): warning: Ignoring bundle <file:///usr/lib/lv2/Vex.lv2/>
mod-ui           | lilv_world_load_bundle(): note: Newer version of <urn:juce:Vex> loaded from <file:///usr/lib/lv2/vex.lv2/>
mod-ui           | error: /usr/lib/lv2/Fluida.lv2/Fluida.ttl:48:4: missing ';' or '.'
mod-ui           | lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/Fluida.lv2/Fluida.ttl'
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED
mod-ui           | WARNING:tornado.general:Connect error on fd 20: ECONNREFUSED
^CGracefully stopping... (press Ctrl+C again to force)
Stopping mod-ui ... done
```

**Comment by rusk911** [comment]
```
~/mod-docker$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Track [Fast Track], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 11: HDMI 5 [HDMI 5]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: NVidia [HDA NVidia], device 12: HDMI 6 [HDMI 6]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

**Comment by rusk911** [comment]
```
~/mod-docker$ jack_lsp
system:capture_1
system:capture_2
system:playback_1
system:playback_2
a2j:Midi Through [14] (capture): Midi Through Port-0
a2j:Midi Through [14] (playback): Midi Through Port-0
PulseAudio JACK Sink-01:front-left
PulseAudio JACK Sink-01:front-right
PulseAudio JACK Source-01:front-left
PulseAudio JACK Source-01:front-right
```

**Comment by raidolo** [comment]
> mod-ui           | mod-host ready!

It's not an issue with the audio card, cause mod-host connects to Jack, otherwise it doesn't start.
Once you launched the docker, could you please run a "netstat -an |grep LISTENING"  so see if the network ports are open? 
Do you have something else on port 8081 or 8888 on your host?
The error is thrown when you open the gui via the browser ot it appears doing nothing else? On which IP are you trying to access?

Thanks.

**Comment by rusk911** [comment]
Not on my pc now, but both ports are used by running containers. 8081 shows
mod folders in browser, 8888 shows mod-ui with error page.

**Comment by raidolo** [comment]
> Not on my pc now, but both ports are used by running containers. 8081 shows
> mod folders in browser, 8888 shows mod-ui with error page.
> 

But what is the error you have in the browser? General error like 404, or do you see the MOD background with a purple sign in the middle?

**Comment by raidolo** [comment]
> Not on my pc now, but both ports are used by running containers. 8081 shows
> mod folders in browser, 8888 shows mod-ui with error page.
> 

Also, you could do a ps -ef or login inside the container with "docker exec -it mod-ui bash" and see there is the python process of the mod-ui is running. It's "python3 server.py". Let me know

**Comment by rusk911** [comment]
All processes within container are:
```
root@cb673750673a:/var/log# ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        SLsl   0:03 python3 /mod/mod-ui/server.py
     21 ?        SLl    0:02 /usr/local/bin/mod-midi-merger-standalone
     28 ?        Z      0:00 [mod-host] <defunct>
     52 ?        S      0:00 /mod/mod-ui/modui-env/bin/python /mod/mod-ui/modui-env/bin/browsepy --directory /mod/user-files --upload /mod/user-files --removable /mod/user-files 0.0.0.0 8081
     72 pts/0    Ss     0:00 bash
     89 pts/0    R+     0:00 ps ax
``` 
error page shows MOD background with "Disconnected" message and "Reload" button.
No any usable logs in /var/log

In container output there are continuously repeating lines I wrote above. But sometimes appearing wierd thing looking like this:

```
mod-ui           | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED
mod-ui           | WARNING:tornado.general:Connect error on fd 21: ECONNREFUSED
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           |  to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to do
mod-ui           | jack client activated before, nothing to WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED
mod-ui           | WARNING:tornado.general:Connect error on fd 21: ECONNREFUSED
mod-ui           | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO
mod-ui           | WARNING:tornado.general:Connect error on fd 24: ECONNREFUSED
mod-ui           | WARNING:tornado.general:Connect error on fd 21: ECONNREFUSED

```

**Comment by rusk911** [comment]
Just for information. In Claudia I see mod-midi-merger connected to default midi port.

**Comment by raidolo** [comment]
> 28 ?        Z      0:00 [mod-host] <defunct>

I don't like this. It seems that mod-host has crashed. That's why you see the MOD UI but then it can't connect to mod-host.

This is what I have: 

```
root@7a077fc4b9a0:/mod# ps -ef |grep mod
abc            1       0  8 09:38 ?        00:00:02 python3 /mod/mod-ui/server.py
abc           22       1  0 09:38 ?        00:00:00 /usr/local/bin/mod-midi-merger-standalone
abc           30       1 21 09:38 ?        00:00:04 mod-host -p 5555 -f 5556
abc           53       1  0 09:38 ?        00:00:00 /mod/mod-ui/modui-env/bin/python /mod/mod-ui/modui-env/bin/browsepy --directory /mod/user-files --upload /mod/user-files --removable /mod/user-files 0.0.0.0 8081
root         107      99  0 09:39 pts/0    00:00:00 grep mod
root@7a077fc4b9a0:/mod#
```

You don't see any "mod-host" in the JACK graph in Carla right? 
Could you login inside the container and launch mod-host manually? 

`# gosu 1000 mod-host -p 5555 -f 5556`

**Comment by rusk911** [comment]
Yes it's crashing. But seems like mod-ui somehow draw both defunct and running processes. In browser I see my pedalboard at background, then gray overlay with "Disconnected" message and "Reload" button.
mod-host output is:

```
# gosu 1000 mod-host -p 5555 -f 5556 -n -v
lilv_world_load_bundle(): warning: Replacing version 0.0 of <http://code.google.com/p/amsynth/amsynth> from <file:///usr/lib/x86_64-linux-gnu/lv2/amsynth.lv2/>
lilv_world_load_bundle(): note: New version 1.5 found in <file:///usr/lib/lv2/amsynth.lv2/>
lilv_world_load_bundle(): warning: Ignoring bundle <file:///usr/lib/lv2/Vex.lv2/>
lilv_world_load_bundle(): note: Newer version of <urn:juce:Vex> loaded from <file:///usr/lib/lv2/vex.lv2/>
mod-host ready!
PROTOCOL: received 'monitor_midi_program' '0' '1'
PROTOCOL: response 'resp 0'
PROTOCOL: received 'monitor_midi_program' '1' '1'
PROTOCOL: response 'resp 0'
PROTOCOL: received 'state_tmpdir' '/mod/data/pedalboard-tmp-data'
PROTOCOL: response 'resp 0'
PROTOCOL: received 'transport' '0' '4.000000' '120.000000'
PROTOCOL: response 'resp 0'
PROTOCOL: received 'add' 'http://guitarix.sourceforge.net/plugins/gxts9#ts9sim' '8'
PROTOCOL: response 'resp 8'
PROTOCOL: received 'add' 'https://mod.audio/plugins/CabinetLoader' '3'
Thread setup with realtime priority successful
PROTOCOL: response 'resp 3'
PROTOCOL: received 'add' 'http://github.com/mikeoliphant/neural-amp-modeler-lv2' '7'
Illegal instruction (core dumped)

```

**Comment by raidolo** [comment]
> Illegal instruction (core dumped)

Ok, let's try to clear things up, I believe there's something bad with the pedalboard. 
Go to /home/$USER_NAME/mod-pedalboards and remove every directory there. The default pedalboard will be recreated. Then start again the container.

**Comment by rusk911** [comment]
so it's because of neural amp modeler. Which is working fine natively in host system and which was working first day I played with mod-docker. Now gxCabinet is working fine but NAM is broken. mod-host crashing after I add NAM to the pedalboard. I don't think we have to continue spending time on this because it's not a very good solution to run audio plugins in docker containers just for pedalboard UI. Is there any discussion on native app you mentioned above?

**Comment by raidolo** [comment]
> so it's because of neural amp modeler. Which is working fine natively in host system and which was working first day I played with mod-docker. Now gxCabinet is working fine but NAM is broken. mod-host crashing after I add NAM to the pedalboard. I don't think we have to continue spending time on this because it's not a very good solution to run audio plugins in docker containers just for pedalboard UI. Is there any discussion on native app you mentioned above?

What cpu do you have? 
I think it's because I've pushed NAM with the optimization fox X64 but it needs a modern CPU more recent than Intel Haswell arch...

**Comment by raidolo** [comment]
> Is there any discussion on native app you mentioned above?

It's in the MOD Forum: https://forum.mod.audio/t/introducing-the-mod-app-for-desktops-beta-release/10495/92

**Comment by raidolo** [comment]
> I don't think we have to continue spending time on this because it's not a very good solution to run audio plugins in docker containers just for pedalboard UI

I agree, I just did it because I wanted to have it portable enough like a single app to launch, but because now they are developing actively the desktop app, mod-docker will not be needed in the future and I will not rebuild it. It's also difficult to maintain because building all the plugins takes a huge amount of time. Thanks for spending some time with it. I'd suggest you to start looking at the mod-app. It's currently a bit buggy because it's in early stages of development, but it works, the midi part is a bit lacking right now but they are developing it.

**Comment by rusk911** [comment]
> > so it's because of neural amp modeler. Which is working fine natively in host system and which was working first day I played with mod-docker. Now gxCabinet is working fine but NAM is broken. mod-host crashing after I add NAM to the pedalboard. I don't think we have to continue spending time on this because it's not a very good solution to run audio plugins in docker containers just for pedalboard UI. Is there any discussion on native app you mentioned above?
> 
> What cpu do you have? I think it's because I've pushed NAM with the optimization fox X64 but it needs a modern CPU more recent than Intel Haswell arch...

Yes it should be it. I have G3260 CPU. Will it be solved if I build the image on my PC? Or do I need to twick some build parameter first? I'm not very familiar with c/cpp development and can't find it myself.

**Comment by raidolo** [comment]
Well I can roll back the NAM part in another image tag if you want to use it, I should be able to do it and I think I have the image somewhere.
Do you want me to do it? Did you play with the mod-app then?

**Comment by rusk911** [comment]
I would like to have nice pedalboard interface on my desktop if it will be compatibile with desktop app, which is under development for now, and with rpi device which i'm planning to build in future.
Just please tell me  which parameter I have to change, I can build the image myself locally and use it.
BTW, desktop version of NAM LV2 works like a charm, does it mean it's not using this optimization?

**Comment by raidolo** [comment]
> Just please tell me which parameter I have to change, I can build the image myself locally and use it.
> BTW, desktop version of NAM LV2 works like a charm, does it mean it's not using this optimization?

It will take forever to build everything. I've done it for you.
I've pushed the image raidolo/mod-ui:namoldcpu, just change thise lines:

in the run_docker.sh change the line: 
`docker pull raidolo/mod-ui:latest`

to 
`docker pull raidolo/mod-ui:namoldcpu`

and in the docker-compose.yml change the line: 

```
  mod-ui-docker:
    image: raidolo/mod-ui:latest
```
to 

```
  mod-ui-docker:
    image: raidolo/mod-ui:namoldcpu
```

Then run ./run_docker.sh, docker maybe could complain that you changed the image for the same container, say Y the first time it asks for confirmation.

Let me know.

Cheers.

**Comment by rusk911** [comment]
Thank you. Running mod-app build for now. Will see what will work first.

**Comment by raidolo** [comment]
> Thank you. Running mod-app build for now. Will see what will work first.

Ok! Download the latest build of mod-app from the GitHub actions. The release 0.0.2 was pretty buggy  for me. My docker has functioning midi if you need it.

**Comment by rusk911** [comment]
suddenly got an i5-4430. Now NAM works with latest image. That's wierd because both CPUs are Haswells.
Anyway, closing the issue because initial problem is solved. gx-cabinet is working well.
